data.raw["solar-panel"]["solar-panel"].fast_replaceable_group = "solar-panel"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "advanced-solar"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "thin-film-solar"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "polycrystalline-solar"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "monocrystalline-solar"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "advanced-monocrystalline-solar"
data.raw["solar-panel"]["solar-panel"].next_upgrade = "passive-emitter-solar"